# Generated by Django 3.2.4 on 2021-06-15 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id_assistant', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=50, null=True)),
                ('Age', models.IntegerField()),
                ('Sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=50)),
                ('Téléphone', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=200)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('heure_debut', models.TimeField(default='20:00')),
                ('heure_fin', models.TimeField(default='21:00')),
                ('Sang', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=50)),
                ('En_Travail', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('valeur', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Date_travail',
            fields=[
                ('id_jour', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_Patient', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=50, null=True)),
                ('Age', models.IntegerField()),
                ('Sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=50)),
                ('Téléphone', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('Sang', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=100)),
                ('Act', models.CharField(choices=[('hospitalisé', 'hospitalisé'), ('visite', 'visite')], default='hospitalisé', max_length=50)),
                ('Date_visite', models.DateField(blank=True, null=True)),
                ('valeur', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ressource_Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('quantié', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nemero_salle', models.IntegerField()),
                ('Numero_lits', models.IntegerField()),
                ('Etage', models.IntegerField()),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ressource_Humains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50, null=True)),
                ('Type', models.CharField(max_length=50, null=True)),
                ('heure_debut', models.TimeField(default='00:00')),
                ('heure_fin', models.TimeField(default='00:00')),
                ('valeur', models.IntegerField(default=1)),
                ('jourtravail', models.ManyToManyField(blank=True, related_name='jour_travail_hr', to='hospitalisation.Date_travail')),
            ],
        ),
        migrations.CreateModel(
            name='Médcin',
            fields=[
                ('id_Médcin', models.AutoField(primary_key=True, serialize=False)),
                ('specialite', models.CharField(choices=[('L’allergologie', 'L’allergologie'), ('L’anesthésiologie.', 'L’anesthésiologie.'), ('L’andrologie.', ' L’andrologie.'), ('La cardiologie.', 'La cardiologie.'), (' La chirurgie.', ' La chirurgie.'), ('La chirurgie cardiaque.', 'La chirurgie cardiaque.'), (' La chirurgie esthétique,', ' La chirurgie esthétique,'), ('La chirurgie générale.', 'La chirurgie générale.'), ('La chirurgie maxillo-faciale.', 'La chirurgie maxillo-faciale.'), (' La chirurgie pédiatrique.', ' La chirurgie pédiatrique.'), (' La chirurgie thoracique.', ' La chirurgie thoracique.'), (' La chirurgie vasculaire.', ' La chirurgie vasculaire.'), (' La neurochirurgie.', ' La neurochirurgie.'), (' La dermatologie.', ' La dermatologie.'), (' L’endocrinologie.', ' L’endocrinologie.'), (' La gastro-entérologie.', ' La gastro-entérologie.'), ('La gériatrie.', 'La gériatrie'), ('La gynécologie.', 'La gynécologie'), ('L’hématologie.', 'L’hématologie'), ('L’hépatologie.', 'L’hépatologie'), ('L’infectiologie.', 'L’infectiologie'), ('La médecine aiguë.', 'La médecine aiguë.'), ('La médecine du travail.', 'La médecine du travail.'), ('La médecine générale.', 'La médecine générale.'), (' La médecine interne.', ' La médecine interne.'), ('  La médecine nucléaire.', '  La médecine nucléaire.'), (' La médecine palliative.', ' La médecine palliative.'), ('La médecine physique.', 'La médecine physique.'), ('La médecine préventive.', 'La médecine préventive.'), ('La néonatologie.', 'La néonatologie.'), ('La néphrologie.', 'La néphrologie.'), ('La neurologie.', 'La neurologie'), (' L’odontologie.', ' L’odontologie'), (' L’oncologie.', ' L’oncologie'), (' L’obstétrique.', ' L’obstétrique'), ('L’ophtalmologie.', 'L’ophtalmologie'), (' L’orthopédie.', ' L’orthopédie'), ('L’Oto-rhino-laryngologie.', 'L’Oto-rhino-laryngologie'), ('La pédiatrie.', 'La pédiatrie'), (' La pneumologie.', ' La pneumologie'), ('La psychiatrie.', 'La psychiatrie'), ('La radiologie.', 'La radiologie'), ('La radiothérapie.', 'La radiothérapie'), ('La rhumatologie', 'La rhumatologie'), ('L’urologie', 'L’urologie')], max_length=50)),
                ('Nom', models.CharField(max_length=50, null=True)),
                ('Age', models.IntegerField()),
                ('Sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=50)),
                ('Téléphone', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=200)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('Sang', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=50)),
                ('heure_debut', models.TimeField(default='20:00')),
                ('heure_fin', models.TimeField(default='21:00')),
                ('En_Travail', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('valeur', models.IntegerField(default=1)),
                ('jourtravail', models.ManyToManyField(blank=True, related_name='date_travail_medcin', to='hospitalisation.Date_travail')),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Entrée', models.DateField(blank=True, null=True)),
                ('Date_Sortie', models.DateField(blank=True, null=True)),
                ('valeur', models.IntegerField(default=1)),
                ('Salle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalisation.salle')),
                ('assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalisation.assistant')),
                ('materiel', models.ManyToManyField(to='hospitalisation.Ressource_Materiel')),
                ('médcin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalisation.médcin')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalisation.patient')),
            ],
        ),
        migrations.AddField(
            model_name='assistant',
            name='jour_travail',
            field=models.ManyToManyField(blank=True, related_name='jour_travail_assistant', to='hospitalisation.Date_travail'),
        ),
    ]
