# Generated by Django 3.2.4 on 2021-06-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Act',
            new_name='Etat',
        ),
    ]
