# Generated by Django 3.2.4 on 2021-06-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0002_rename_act_patient_etat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ressource_Humains',
        ),
    ]
